language: shell

sudo: false

install:
  - npm install -g remark-cli
  - npm install --save remark-cli remark-preset-lint-recommended

jobs:
  include:
    - stage: bash linting
      script: bash -c 'shopt -s globstar; shellcheck *.sh'
    - stage: markdown linting
      script: remark . --use preset-lint-recommended
