language: shell

sudo: false

install:
  - gem install mdl
    
jobs:
  include:
    - stage: bash linting
      script: bash -c 'shopt -s globstar; shellcheck *.sh'
    - stage: markdown linting
      script: mdl . 
