language: shell

sudo: false

jobs:
  include:
    - stage: bash linting
      script: bash -c 'shopt -s globstar; shellcheck *.sh'
    - stage: markdown linting
      script: remark . --use preset-lint-recommended --ignore-path .remark_ignore --frail
      install:
        - npm install -g remark-cli remark-preset-lint-recommended
    - stage: testing setup.sh on Linux
      os: linux
      language: shell
      script: ./setup.sh
      env:
        - test_environment: true
    - stage: testing setup.sh on Mac
      os: osx
      language: shell
      script: ./setup.sh
