language: shell

sudo: false

install:
  - npm install -g remark-cli remark-preset-lint-recommended

env:
  - test_environment=true:

jobs:
  include:
    - stage: bash linting
      script: bash -c 'shopt -s globstar; shellcheck *.sh'
    - stage: markdown linting
      script: remark . --use preset-lint-recommended --ignore-path .remark_ignore --frail
    - stage: testing setup.sh on Linux
      os: linux
      language: shell
      script: ./setup.sh
    - stage: testing setup.sh on Mac
      os: osx
      language: shell
      script: ./setup.sh
